"""Migration 3: Add StreamingSubscription table

Revision ID: 84a7b665dde9
Revises: c1f026e9ccc2
Create Date: 2025-09-26 10:39:47.892266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a7b665dde9'
down_revision: Union[str, Sequence[str], None] = 'c1f026e9ccc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_streaming_subscription_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streaming_subscription'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaming_subscription')
    # ### end Alembic commands ###
