"""Migration 2: Add streaming_available to film

Revision ID: c1f026e9ccc2
Revises: ed90e0dffeb6
Create Date: 2025-09-26 10:39:16.098537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f026e9ccc2'
down_revision: Union[str, Sequence[str], None] = 'ed90e0dffeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('streaming_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'streaming_available')
    # ### end Alembic commands ###
